// Lista de compras mensal baseada no Plano Nutricional Tático 2300 kcal
// Período: 30 dias | Cada uma das 5 opções de cada refeição é usada ~6x no mês

export type Category =
  | "Proteínas"
  | "Laticínios"
  | "Carboidratos"
  | "Frutas"
  | "Vegetais"
  | "Gorduras"
  | "Suplementos"
  | "Padaria"
  | "Bebidas"
  | "Outros"

export interface ShoppingItem {
  id: string
  name: string
  quantity: number
  unit: string
  category: Category
  price: number
  tip?: string
  substitutes?: string[]
  checked: boolean
}

export interface MealSection {
  id: string
  name: string
  emoji: string
  target: string
  description: string
  items: ShoppingItem[]
}

export const categoryColors: Record<Category, string> = {
  Proteínas: "bg-red-100 text-red-700 border-red-200 dark:bg-red-950 dark:text-red-300 dark:border-red-900",
  Laticínios: "bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-900",
  Carboidratos: "bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-950 dark:text-orange-300 dark:border-orange-900",
  Frutas: "bg-green-100 text-green-700 border-green-200 dark:bg-green-950 dark:text-green-300 dark:border-green-900",
  Vegetais: "bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-950 dark:text-emerald-300 dark:border-emerald-900",
  Gorduras: "bg-yellow-100 text-yellow-700 border-yellow-200 dark:bg-yellow-950 dark:text-yellow-300 dark:border-yellow-900",
  Suplementos: "bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-950 dark:text-purple-300 dark:border-purple-900",
  Padaria: "bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-900",
  Bebidas: "bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-950 dark:text-blue-300 dark:border-blue-900",
  Outros: "bg-gray-100 text-gray-700 border-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-700",
}

export const categoryEmoji: Record<Category, string> = {
  Proteínas: "🥩",
  Laticínios: "🥛",
  Carboidratos: "🍚",
  Frutas: "🍎",
  Vegetais: "🥦",
  Gorduras: "🫒",
  Suplementos: "💪",
  Padaria: "🍞",
  Bebidas: "🥤",
  Outros: "📦",
}

export const meals: MealSection[] = [
  {
    id: "cafe",
    name: "Café da Manhã",
    emoji: "🌅",
    target: "~260 kcal | 25P | 25C | 8G",
    description: "Desjejum — baixo volume e digestão limpa. Ativação rápida de aminoácidos.",
    items: [
      {
        id: "cafe-1",
        name: "Ovos inteiros",
        quantity: 24,
        unit: "unid",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Prefira ovos caipiras ou de galinhas livres de gaiola. Verifique a validade e conserve na geladeira.",
        substitutes: ["Clara de ovo pasteurizada", "Ovos de codorna (3 = 1 ovo)"],
      },
      {
        id: "cafe-2",
        name: "Claras de ovo (extras)",
        quantity: 12,
        unit: "unid",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Pode comprar cartela de claras pasteurizadas para maior praticidade.",
        substitutes: ["Clara pasteurizada líquida (aprox. 30ml = 1 clara)"],
      },
      {
        id: "cafe-3",
        name: "Pão 100% integral",
        quantity: 150,
        unit: "g",
        category: "Padaria",
        price: 0,
        checked: false,
        tip: "Confira o rótulo: o primeiro ingrediente deve ser farinha integral. Wickbold 100% Integral é uma boa opção.",
        substitutes: ["Pão francês integral", "Tapioca (goma hidratada)"],
      },
      {
        id: "cafe-4",
        name: "Whey Protein",
        quantity: 360,
        unit: "g",
        category: "Suplementos",
        price: 0,
        checked: false,
        tip: "Sabor baunilha ou chocolate para versatilidade. Compre pote de 900g-1kg. Verifique selo de pureza (Informed Choice).",
        substitutes: ["Albumina", "Caseína", "Blend proteico"],
      },
      {
        id: "cafe-5",
        name: "Leite desnatado",
        quantity: 1200,
        unit: "ml",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Caixa de 1L tetrapak tem validade maior após abertura. Considere UHT.",
        substitutes: ["Leite de amêndoas sem açúcar", "Leite de soja"],
      },
      {
        id: "cafe-6",
        name: "Aveia em flocos",
        quantity: 90,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Flocos finos para mingau. Marca a granel sai mais barato.",
        substitutes: ["Farelo de aveia", "Quinoa em flocos"],
      },
      {
        id: "cafe-7",
        name: "Iogurte desnatado natural",
        quantity: 900,
        unit: "g",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Potes de 170g ou 1kg. Confira: sem açúcar adicionado.",
        substitutes: ["Iogurte grego 0% gordura", "Kefir"],
      },
      {
        id: "cafe-8",
        name: "Sementes de chia",
        quantity: 60,
        unit: "g",
        category: "Outros",
        price: 0,
        checked: false,
        tip: "Compra a granel sai mais barato. Hidrate em água antes de consumir.",
        substitutes: ["Sementes de linhaça", "Psyllium"],
      },
      {
        id: "cafe-9",
        name: "Goma de tapioca",
        quantity: 120,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Goma hidratada de mandioca. Sem glúten.",
        substitutes: ["Massa de tapioca pronta", "Polvilho doce"],
      },
      {
        id: "cafe-10",
        name: "Queijo minas frescal",
        quantity: 900,
        unit: "g",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Versão 'light' ou 'frescal' tem menos sódio. Conserve na geladeira.",
        substitutes: ["Queijo cottage", "Ricota light"],
      },
      {
        id: "cafe-11",
        name: "Mamão papaia",
        quantity: 600,
        unit: "g",
        category: "Frutas",
        price: 0,
        checked: false,
        tip: "Escolha os firmes, sem manchas. Amadurece em temperatura ambiente.",
        substitutes: ["Mamão formosa", "Banana", "Melão"],
      },
    ],
  },
  {
    id: "lanche-manha",
    name: "Lanche da Manhã",
    emoji: "🥪",
    target: "~220 kcal | 20P | 15C | 8G",
    description: "Logística simplificada — opções de bolso para consumo rápido no trabalho.",
    items: [
      {
        id: "lm-1",
        name: "Whey Protein (extra)",
        quantity: 180,
        unit: "g",
        category: "Suplementos",
        price: 0,
        checked: false,
        tip: "Incluído na conta total de Whey do café da manhã. Pode ser o mesmo pote.",
        substitutes: ["Barra de proteína", "Iogurte proteico"],
      },
      {
        id: "lm-2",
        name: "Castanha de caju",
        quantity: 90,
        unit: "g",
        category: "Gorduras",
        price: 0,
        checked: false,
        tip: "Sem sal adicionado. Compre a granel para economizar.",
        substitutes: ["Amêndoas", "Castanha-do-pará", "Nozes"],
      },
      {
        id: "lm-3",
        name: "Barra de proteína",
        quantity: 6,
        unit: "unid",
        category: "Suplementos",
        price: 0,
        checked: false,
        tip: "Bold Bar ou Nutrata Grego — verifique teor de açúcar (<5g por barra).",
        substitutes: ["Whey + fruta", "Iogurte proteico"],
      },
      {
        id: "lm-4",
        name: "Peito de frango (desfiado)",
        quantity: 480,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Cozinhe e desfie em lote para a semana. Congele porções. Compre peito in natura, não processado.",
        substitutes: ["Atum em água", "Frango desfiado em conserva"],
      },
      {
        id: "lm-5",
        name: "Amendoim torrado sem pele",
        quantity: 120,
        unit: "g",
        category: "Gorduras",
        price: 0,
        checked: false,
        tip: "Sem sal. Verifique frescor — ranço indica oxidação.",
        substitutes: ["Pasta de amendoim integral", "Amêndoas"],
      },
      {
        id: "lm-6",
        name: "Iogurte proteico líquido (YoPro)",
        quantity: 6,
        unit: "unid",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Garrafa de 200ml com 15g de proteína. Compre em combo de 6 para desconto.",
        substitutes: ["Iogurte grego + whey", "Shake de whey"],
      },
      {
        id: "lm-7",
        name: "Amêndoas",
        quantity: 90,
        unit: "g",
        category: "Gorduras",
        price: 0,
        checked: false,
        tip: "Sem sal. Lascas ou inteiras. Verifique validade.",
        substitutes: ["Castanha de caju", "Nozes"],
      },
      {
        id: "lm-8",
        name: "Maçã",
        quantity: 720,
        unit: "g",
        category: "Frutas",
        price: 0,
        checked: false,
        tip: "Aprox. 6 maçãs médias (120g cada). Escolha firmes e brilhantes.",
        substitutes: ["Pera", "Banana", "Frutas vermelhas"],
      },
    ],
  },
  {
    id: "almoco",
    name: "Almoço",
    emoji: "🍛",
    target: "~440 kcal | 42P | 35C | 12G",
    description: "Volume controlado de carboidratos complexos para evitar letargia à tarde.",
    items: [
      {
        id: "al-1",
        name: "Carne moída (patinho)",
        quantity: 900,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Peça para moer na hora. Corte patinho é magro e econômico. Congele em porções de 300g.",
        substitutes: ["Carne moída de acém", "Frango moído"],
      },
      {
        id: "al-2",
        name: "Arroz integral",
        quantity: 720,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "1 xícara de arroz cru rende ~3 xícaras cozidas. Para 720g cozido, compre ~240g cru.",
        substitutes: ["Arroz branco", "Arroz parboilizado"],
      },
      {
        id: "al-3",
        name: "Peito de frango grelhado",
        quantity: 960,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Compre peito in natura, sem pele. Aprox. 4-5 peças de 250g. Verifique não estar com líquido (retenção de água).",
        substitutes: ["Sobrecoxa sem pele", "Filé de frango"],
      },
      {
        id: "al-4",
        name: "Batata doce",
        quantity: 900,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Tipo inglesa ou rosada. Cozinhe com casca para preservar nutrientes.",
        substitutes: ["Batata inglesa", "Mandioca", "Inhame"],
      },
      {
        id: "al-5",
        name: "Filé de tilápia",
        quantity: 960,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Congelado é mais barato. Verifique se não tem glaze (água congelada). Descongele na geladeira.",
        substitutes: ["Filé de merluza", "Filé de panga", "Salmão"],
      },
      {
        id: "al-6",
        name: "Mandioca",
        quantity: 780,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Compre fresca e congele cozida em porções. Ou mandioca pré-cozida congelada para praticidade.",
        substitutes: ["Batata inglesa", "Inhame", "Batata doce"],
      },
      {
        id: "al-7",
        name: "Lombo suíno",
        quantity: 900,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Corte magro. Aprox. 2kg com osso = 900g limpo. Peça para limpar a capa de gordura.",
        substitutes: ["Lombo de boi (alcatra)", "Filé mignon suíno"],
      },
      {
        id: "al-8",
        name: "Macarrão integral",
        quantity: 720,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "1 pacote de 500g cru rende ~1,2kg cozido. Para 720g cozido, compre ~300g cru.",
        substitutes: ["Macarrão de sêmola", "Macarrão de grão-de-bico", "Penne integral"],
      },
      {
        id: "al-9",
        name: "Molho de tomate caseiro",
        quantity: 300,
        unit: "ml",
        category: "Outros",
        price: 0,
        checked: false,
        tip: "Faça em lote: tomates pelados + cebola + alho + ervas. Congele em porções de 100ml.",
        substitutes: ["Passata de tomate pronta", "Tomate pelado em lata"],
      },
      {
        id: "al-10",
        name: "Arroz branco",
        quantity: 600,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Para 600g cozido, compre ~200g cru. Tipo agulhinha.",
        substitutes: ["Arroz integral", "Arroz parboilizado"],
      },
      {
        id: "al-11",
        name: "Feijão carioca",
        quantity: 300,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "1 xícara de feijão cru (180g) rende ~3 xícaras cozidas (~450g). Para 300g cozido, compre ~120g cru.",
        substitutes: ["Feijão preto", "Lentilha", "Grão-de-bico"],
      },
    ],
  },
  {
    id: "lanche-tarde",
    name: "Lanche da Tarde",
    emoji: "🍵",
    target: "~250 kcal | 25P | 18C | 5G",
    description: "Pré-treino — aporte de energia limpa sem sobrecarregar o estômago.",
    items: [
      {
        id: "lt-1",
        name: "Pão integral (fatiado)",
        quantity: 300,
        unit: "g",
        category: "Padaria",
        price: 0,
        checked: false,
        tip: "Já inclui o pão do café da manhã. Pacote de 500g.",
        substitutes: ["Torradas integrais", "Pão sírio"],
      },
      {
        id: "lt-2",
        name: "Atum em água (lata)",
        quantity: 420,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Latas de 60g escorridas. Compre 7 latas. Verifique 'em água' e não 'em óleo'.",
        substitutes: ["Atum em água (sachê)", "Sardinha em água"],
      },
      {
        id: "lt-3",
        name: "Whey Protein (pré-treino)",
        quantity: 360,
        unit: "g",
        category: "Suplementos",
        price: 0,
        checked: false,
        tip: "Mesmo pote do café da manhã. Some os 360g ao total.",
        substitutes: ["BCAA", "Albumina"],
      },
      {
        id: "lt-4",
        name: "Banana prata",
        quantity: 480,
        unit: "g",
        category: "Frutas",
        price: 0,
        checked: false,
        tip: "Aprox. 6 bananas médias (80g). Compre verdes e deixe amadurecer em casa.",
        substitutes: ["Banana nanica", "Banana maçã"],
      },
      {
        id: "lt-5",
        name: "Iogurte proteico (pote)",
        quantity: 6,
        unit: "unid",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Potes de 150g com 15g de proteína. Compre em combo.",
        substitutes: ["Iogurte grego 0%", "Iogurte desnatado + whey"],
      },
      {
        id: "lt-6",
        name: "Aveia em flocos (extra)",
        quantity: 270,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Mesmo pacote do café da manhã. Some os 270g ao total.",
        substitutes: ["Granola sem açúcar", "Quinoa em flocos"],
      },
      {
        id: "lt-7",
        name: "Peito de frango desfiado (extra)",
        quantity: 600,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Mesmo lote do almoço. Cozinhe e desfie em lote.",
        substitutes: ["Atum", "Frango em conserva"],
      },
      {
        id: "lt-8",
        name: "Batata inglesa (purê)",
        quantity: 480,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Para purê sem leite/creme (apenas água e sal). Aprox. 4 batatas médias.",
        substitutes: ["Batata doce", "Mandioca"],
      },
      {
        id: "lt-9",
        name: "Ovos (panqueca)",
        quantity: 6,
        unit: "unid",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Já incluído na conta de ovos do café da manhã.",
        substitutes: ["Clara de ovo líquida"],
      },
    ],
  },
  {
    id: "jantar",
    name: "Jantar",
    emoji: "🍽️",
    target: "~850 kcal | 70P | 70C | 26G",
    description: "A GRANDE REFEIÇÃO — hipertrofia, saciedade noturna e carga máxima de nutrientes.",
    items: [
      {
        id: "ja-1",
        name: "Alcatra ou Contrafilé (limpo)",
        quantity: 1320,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Peça para retirar a capa de gordura. Aprox. 3 peças de 440g. Congele em porções individuais.",
        substitutes: ["Fraldinha", "Maminha", "Patinho bovino"],
      },
      {
        id: "ja-2",
        name: "Arroz branco (grande refeição)",
        quantity: 1500,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Para 1,5kg cozido, compre ~500g cru. Sacos de 1kg rendem bem.",
        substitutes: ["Arroz integral", "Arroz parboilizado"],
      },
      {
        id: "ja-3",
        name: "Feijão carioca (jantar)",
        quantity: 600,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Para 600g cozido, compre ~240g cru. Cozinhe em lote para a semana.",
        substitutes: ["Feijão preto", "Lentilha"],
      },
      {
        id: "ja-4",
        name: "Pão de hambúrguer tradicional",
        quantity: 6,
        unit: "unid",
        category: "Padaria",
        price: 0,
        checked: false,
        tip: "Pode ser integral. Verifique ingredientes — evite açúcar no topo da lista. Congele.",
        substitutes: ["Pão integral", "Pão brioche"],
      },
      {
        id: "ja-5",
        name: "Carne moída para hambúrguer (patinho)",
        quantity: 1320,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Moída na hora. Para hambúrguer caseiro: tempere com sal, alho, cebola. Modele e congele.",
        substitutes: ["Carne moída de acém", "Blended de frango e boi"],
      },
      {
        id: "ja-6",
        name: "Queijo muçarela fatiado",
        quantity: 240,
        unit: "g",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Pacote de 250g ou fatiado na hora. Muçarela light tem menos gordura.",
        substitutes: ["Queijo prato", "Queijo muçarela light", "Queijo minas"],
      },
      {
        id: "ja-7",
        name: "Tomate",
        quantity: 300,
        unit: "g",
        category: "Vegetais",
        price: 0,
        checked: false,
        tip: "Aprox. 3 tomates médios. Escolha firmes e vermelhos.",
        substitutes: ["Tomate cereja", "Tomate italiano"],
      },
      {
        id: "ja-8",
        name: "Peito de frango (jantar)",
        quantity: 1500,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Aprox. 6 peças de 250g. Combine com a compra do almoço para economizar em atacado.",
        substitutes: ["Sobrecoxa sem pele", "Coxa de frango sem pele"],
      },
      {
        id: "ja-9",
        name: "Batata inglesa (airfryer)",
        quantity: 2100,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Aprox. 2 sacos de 1kg. Para airfryer: corte em palito, tempere com sal e azeite.",
        substitutes: ["Batata doce", "Mandioca", "Batata rústica"],
      },
      {
        id: "ja-10",
        name: "Azeite de oliva extra virgem",
        quantity: 132,
        unit: "ml",
        category: "Gorduras",
        price: 0,
        checked: false,
        tip: "Uma garrafa de 200ml ou use da cozinha. Acidez <0,5%. Verifique 'extra virgem' no rótulo.",
        substitutes: ["Azeite de oliva", "Óleo de abacate"],
      },
      {
        id: "ja-11",
        name: "Macarrão de sêmola",
        quantity: 1080,
        unit: "g (cozido)",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Para 1,08kg cozido, compre ~360g cru. Pacote de 500g.",
        substitutes: ["Macarrão integral", "Penne", "Espaguete"],
      },
      {
        id: "ja-12",
        name: "Queijo parmesão ralado",
        quantity: 120,
        unit: "g",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Rale na hora para mais sabor. Ou compre em pedaço e rale conforme uso.",
        substitutes: ["Queijo grana padano", "Queijo pecorino"],
      },
      {
        id: "ja-13",
        name: "Lombo suíno (jantar)",
        quantity: 1500,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Aprox. 1,5kg. Pode comprar peça inteira e dividir. Mais barato que boi.",
        substitutes: ["Lombo de boi", "Pernil suíno magro"],
      },
      {
        id: "ja-14",
        name: "Mandioca (jantar)",
        quantity: 1500,
        unit: "g",
        category: "Carboidratos",
        price: 0,
        checked: false,
        tip: "Pré-cozida congelada é prática. Ou compre fresca e cozinhe em lote.",
        substitutes: ["Batata inglesa", "Inhame"],
      },
      {
        id: "ja-15",
        name: "Manteiga ou azeite",
        quantity: 90,
        unit: "g",
        category: "Gorduras",
        price: 0,
        checked: false,
        tip: "Manteiga sem sal para cozimento. Ou use o azeite já comprado.",
        substitutes: ["Ghee", "Margarina"],
      },
    ],
  },
  {
    id: "ceia",
    name: "Ceia",
    emoji: "🌙",
    target: "~250 kcal | 25P | 7C | 12G",
    description: "Pré-sono — gorduras saudáveis e proteínas de digestão lenta para balanço nitrogenado positivo.",
    items: [
      {
        id: "ce-1",
        name: "Ovos (ceia)",
        quantity: 18,
        unit: "unid",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Somar aos ovos do café da manhã. Total mensal de ovos: ~48 unid.",
        substitutes: ["Ovos de codorna", "Claras pasteurizadas"],
      },
      {
        id: "ce-2",
        name: "Chá de camomila ou erva-doce (sachês)",
        quantity: 6,
        unit: "sachês",
        category: "Bebidas",
        price: 0,
        checked: false,
        tip: "Sem açúcar. Caixa com 20 sachês.",
        substitutes: ["Chá de erva-cidreira", "Chá de mulungu", "Chá verde descafeinado"],
      },
      {
        id: "ce-3",
        name: "Abacate",
        quantity: 600,
        unit: "g",
        category: "Frutas",
        price: 0,
        checked: false,
        tip: "Aprox. 3 abacates pequenos. Compre verdes e deixe amadurecer. Congele a polpa em porções.",
        substitutes: ["Pasta de amendoim", "Castanhas"],
      },
      {
        id: "ce-4",
        name: "Whey Protein sabor chocolate",
        quantity: 300,
        unit: "g",
        category: "Suplementos",
        price: 0,
        checked: false,
        tip: "Pode ser o mesmo pote de baunilha (sabor neutro). Some ao total de whey.",
        substitutes: ["Caseína", "Albumina"],
      },
      {
        id: "ce-5",
        name: "Iogurte grego tradicional",
        quantity: 600,
        unit: "g",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Pote de 500g ou 1kg. Verifique: 'tradicional' tem mais proteína que 'light'.",
        substitutes: ["Iogurte natural integral", "Skyr"],
      },
      {
        id: "ce-6",
        name: "Sementes de chia (extra)",
        quantity: 60,
        unit: "g",
        category: "Outros",
        price: 0,
        checked: false,
        tip: "Mesmo pacote do café da manhã.",
        substitutes: ["Sementes de linhaça", "Psyllium"],
      },
      {
        id: "ce-7",
        name: "Albumina ou Caseína",
        quantity: 180,
        unit: "g",
        category: "Suplementos",
        price: 0,
        checked: false,
        tip: "Caseína é mais cara mas tem digestão lenta (ideal para ceia). Albumina é mais barata.",
        substitutes: ["Whey Protein", "Blend noturno"],
      },
      {
        id: "ce-8",
        name: "Pasta de amendoim integral",
        quantity: 90,
        unit: "g",
        category: "Gorduras",
        price: 0,
        checked: false,
        tip: "100% amendoim, sem açúcar e sem óleo de palma. Pote de 1kg rende muito.",
        substitutes: ["Pasta de amêndoas", "Pasta de castanha"],
      },
      {
        id: "ce-9",
        name: "Peito de frango desfiado (ceia)",
        quantity: 600,
        unit: "g",
        category: "Proteínas",
        price: 0,
        checked: false,
        tip: "Mesmo lote dos outros horários. Some ao total de frango do mês.",
        substitutes: ["Atum", "Frango em conserva"],
      },
      {
        id: "ce-10",
        name: "Queijo minas (ceia)",
        quantity: 180,
        unit: "g",
        category: "Laticínios",
        price: 0,
        checked: false,
        tip: "Mesma peça do café da manhã.",
        substitutes: ["Queijo cottage", "Ricota"],
      },
    ],
  },
]

// Itens consolidados (para o resumo de totais)
export const consolidatedItems = [
  { name: "Ovos inteiros (total)", total: 48, unit: "unid", category: "Proteínas" as Category },
  { name: "Peito de frango (total)", total: 4140, unit: "g", category: "Proteínas" as Category },
  { name: "Whey Protein (total)", total: 1200, unit: "g", category: "Suplementos" as Category },
  { name: "Aveia em flocos (total)", total: 360, unit: "g", category: "Carboidratos" as Category },
  { name: "Arroz (total)", total: 2820, unit: "g cozido", category: "Carboidratos" as Category },
  { name: "Feijão (total)", total: 900, unit: "g cozido", category: "Carboidratos" as Category },
  { name: "Carne moída (total)", total: 2220, unit: "g", category: "Proteínas" as Category },
]
